<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- ✅ Application supporte Windows 7 (6.1) et supérieur -->
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <RootNamespace>ChatServer</RootNamespace>
    <AssemblyName>ChatServer</AssemblyName>
    <ApplicationIcon>CamTalk.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CamTalk.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.4" />
  </ItemGroup>

</Project>